### ISSUE TITLE
ES6 -> ES5 in npm package

### ISSUE THREAD

**Issue by kachkaev** [jahredhope/promise-file-reader#4]
I'm using create-react-app and its webpack config does not apply babel to stuff in `node_modules`. The app works in dev mode because Chrome understands ES6 pretty well already, but when I run `yarn build`, this error shows up:

```
Failed to compile.

static/js/main.6494367c.js from UglifyJs
SyntaxError: Unexpected token: operator (>) [./~/promise-file-reader/PromiseFileReader.js:5,0]
```

The reason is `=>` in `index.js`, which is not expected. Could you please move from ES6 to ES5 in the published version?

Thanks for the wrapper! Saves some time re-implementing it in every new project :–)

**Comment by kachkaev** [comment]
I  temporary copied `index.js` to my `src`, so it goes through babel now:

```js
// import {readAsText} from 'promise-file-reader';
import {readAsText} from './lib/promise-file-reader';
```

Relevant discussion:
https://github.com/facebookincubator/create-react-app/issues/1125

**Comment by jahredhope** [comment]
Published
